services:
    qbittorrent:
        image: lscr.io/linuxserver/qbittorrent:latest
        restart: unless-stopped
        ports:
            - 8080:8080
            - 6881:6881
            - 6881:6881/udp
        networks:
            - mediarr
        environment:
            - PUID=1000
            - PGID=1000
            - WEBUI_PORT=8080
        volumes:
            - ./config:/config
            - /data/media/downloads:/downloads
