services:
    prowlarr:
        image: lscr.io/linuxserver/prowlarr:latest
        restart: unless-stopped
        ports:
            - 9696:9696
        networks:
            - mediarr
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./config:/config
        depends_on: 
          - flaresolverr 
    flaresolverr:
        image: ghcr.io/flaresolverr/flaresolverr:latest
        restart: unless-stopped
        ports:
            - 8191:8191
        networks:
            - mediarr
        environment:
            - PUID=1000
            - PGID=1000
            - LOG_LEVEL=${LOG_LEVEL:-info} 
            - LOG_HTML=${LOG_HTML:-false} 
            - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none} 
