services:
    filebrowser:
        image: filebrowser/filebrowser
        restart: unless-stopped
        user: 1000:1000
        ports:
            - "9998:9998"
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - /data:/srv
            - ./config/filebrowser.db:/database.db
            - ./config/filebrowser.json:/.filebrowser.json
