services:
    recyclarr:
        image: ghcr.io/recyclarr/recyclarr
        restart: unless-stopped
        read_only: true
        tmpfs: /tmp
        security_opt: ["no-new-privileges:true"]
        networks:
            - mediarr
        volumes:
            - ./config:/config
        environment:
            - RECYCLARR_CREATE_CONFIG=true
        depends_on:
            - sonarr
            - radarr
