services:
    recyclarr:
        image: ghcr.io/recyclarr/recyclarr
        restart: unless-stopped
        networks:
            - mediarr
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./config:/config
        depends_on:
            - sonarr
            - radarr
