services:
    syncthing:
        image: lscr.io/linuxserver/syncthing:latest
        restart: unless-stopped
        ports:
            - 8384:8384
            - 22000:22000/tcp
            - 22000:22000/udp
            - 21027:21027/udp
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./config:/config
            - /data/sync:/sync
